name = "SeisPGVPGA"
uuid = "5c9eb482-5d9f-4433-a684-eda60c795573"
authors = ["kura-okubo"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
